name: TerraformDeploy
on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  deployInfra:
    runs-on: ubuntu-latest
    env:
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
    steps:
      - name: "Preparar código"
        uses: actions/checkout@v4
      
      - name: "Terraform init"
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        run: terraform apply -auto-approve